#!/bin/bash
set -ex

echo "Running test for HTTP Server app..."

test() {
	port=1234
	if [ "$1" == "$NODE18" ]; then
		container="$(docker run -d --rm -v "$PWD/src":/src:ro -p $port:8080 "$1" /src/main.js)"
	else
		container="$(docker run -d --rm -v "$PWD/src":/src:ro -p $port:8080 "$1" exec node /src/main.js)"
	fi
	sleep 1
	output="$(curl http://localhost:$port/)"
	[ "$output" == "Hello world!" ] || exit 1
}

cleanup() {
	docker stop "$container" || true
}
trap cleanup EXIT

test "$NODE_X"
