#!/bin/bash
set -ex

echo "Running tests..."

export NODE_X=${1:-"ubuntu/chiselled-node:18-test"}
export NODE18="ubuntu/chiselled-node:18-test"
export NODE20="ubuntu/nodejs:20-test"

CURRENT_DIR="$(dirname "$(readlink -f "$0")")"

for test_dir in "$CURRENT_DIR"/*/; do
    pushd "$test_dir"

    ./runtest

    popd
done
