#!/bin/bash
set -ex

echo "Running test for simple JS bundled app with WASM..."

build() {
    npm i
    npm run asbuild
    npm run build
    install -Dvm644 "$PWD/build/release.wasm" "$PWD/dist"
}

test() {
    if [ "$1" == "$NODE18" ]; then
        docker run --rm -v "$PWD/dist":/src:ro "$1" /src/index.mjs
    else
        docker run --rm -v "$PWD/dist":/src:ro "$1" exec node /src/index.mjs
    fi
}

build
test "$NODE_X"
