#!/bin/bash
set -ex

echo "Running test for HTTP Server app..."

build() {
    npm i
    npm run check
    npm run build
}

test() {
	port=1234
	container="$(docker run -d --rm -v "$PWD/dist":/src:ro -p $port:3000 "$1" exec node /src/index.js)"
	sleep 1
	local output expected
	output="$(curl http://localhost:$port/)"
	[ "$output" == "Hello world!" ] || exit 1
    output="$(curl http://localhost:$port/date)"
    expected="$(date +'%Y-%m-%d')"
	[ "$output" == "$expected" ] || exit 1
}

cleanup() {
	docker stop "$container" || true
}
trap cleanup EXIT

build
test "$NODE18"
