#!/bin/bash
set -ex

echo "Running test for simple JS bundled app..."

build() {
    npm i
    npm run build
}

test() {
    if [ "$1" == "$NODE18" ]; then
        docker run --rm -v "$PWD/dist":/src:ro "$1" /src/index.js
    else
        docker run --rm -v "$PWD/dist":/src:ro "$1" exec node /src/index.js
    fi
}

build
test "$NODE_X"
